CREATE DATABASE voli;

USE voli;

CREATE TABLE AEROPORTI
(
 ID_AEROPORTO        INTEGER PRIMARY KEY
,CITTA               VARCHAR(30)
,NAZIONE             VARCHAR(30)
,NUM_PISTE           INTEGER 
);

CREATE TABLE VOLI 
(
 ID_VOLO           INTEGER AUTO_INCREMENT PRIMARY KEY
,GIORNO            DATE
,CITTA_PARTENZA    VARCHAR(50)
,ORA_PARTENZA      TIMESTAMP
,CITTA_ARRIVO      VARCHAR(50)
,ORA_ARRIVO        TIMESTAMP
,TIPO_AEREO        CHAR(5)
, PASSEGGERI 	   INTEGER
, MERCI		   INTEGER
);

CREATE TABLE AEREO
(
 TIPO_AEREO        CHAR(5) PRIMARY KEY
,NUM_PASS          INTEGER
,QTA_MERCI         INTEGER
);
